### ISSUE TITLE
koop add koop-provider-xlsx

### ISSUE THREAD

**Issue by aitorcalero** [ntkog/koop-provider-xlsx#1]
When I use this command I get this error:
`aitor@PCDIR08:~$ koop add koop-provider-xlsx
Not enough non-option arguments: got 1, need at least 2`

**Comment by ntkog** [comment]
Yep. This is for two reasons
- You must to add **provider** keyword between "add" and the name of the module: **koop-provider-xlsx**
- **koop-provider-xlsx** is not published yet as a npm package. Should be **ntkog/koop-provider-xlsx** instead. 

```bash
koop add provider ntkog/koop-provider-xlsx
```

> **koop-cli** doesn't deal yet with packages directly from github. It expects the package was already published in npm. 

Sorry for the mess :-)
